services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather_station
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  data-generator:
    build: .
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: weather_station
      DB_PORT: 3306
    networks:
      - app-network
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: redash
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network
  redis:
    image: redis:6-alpine
    restart: always
    command: redis-server --appendonly yes
    networks:
      - app-network
  redash-create-db:
    image: redash/redash:latest
    environment:
      REDASH_DATABASE_URL: postgresql://postgres:root@postgres/redash
      REDASH_REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    command:
      sh -c "/app/bin/run python /app/manage.py database create_tables && /app/bin/run python /app/manage.py database upgrade"
    networks:
      - app-network
    restart: "no"
  redash-server:
    image: redash/redash:latest
    ports:
      - "5000:5000"
    command: server
    environment:
      REDASH_DATABASE_URL: postgresql://postgres:root@postgres/redash
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_LOG_LEVEL: INFO
      REDASH_COOKIE_SECRET: weather_station_secret
      REDASH_SECRET_KEY: weather_station_secret_key
      REDASH_HOST: http://localhost:5000
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - app-network
  scheduler:
    image: redash/redash:latest
    depends_on:
      - postgres
      - redis
    environment:
      REDASH_LOG_LEVEL: INFO
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_DATABASE_URL: postgresql://postgres:root@postgres/redash
    command: scheduler
    restart: always
    networks:
      - app-network
  scheduled_worker:
    image: redash/redash:latest
    depends_on:
      - postgres
      - redis
    environment:
      REDASH_LOG_LEVEL: INFO
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_DATABASE_URL: postgresql://postgres:root@postgres/redash
    restart: always
    command: worker
    networks:
      - app-network
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - redash-server
    restart: always
    networks:
      - app-network
volumes:
  db_data:
  postgres_data:
networks:
  app-network:
    driver: bridge
